name: money_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_native_splash: ^2.3.9
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  # ✅ Correct package name and latest stable version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ Place inside dev_dependencies

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # ✅ Correct location for app logo
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # ✅ Ensure the logo exists in the assets folder
